#!/bin/bash
SG_ID="sg-04912852a99136d2b"
AMI_ID="ami-0220d79f3f480ecf5"

for instance in $@
do
aws ec2 run-instances 
    --image-id $AMI_ID \
    --instance-type t3.micro \
    --security-gorup-ids $SG_ID
    --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=$Instance}]' \
    --query 'Instances[0].InstanceId'\
    --output text

if [$instance == "fronted" ]; then
    IP=$(
        aws ec2 describe-instances \
         --instance-id $InstanceId  \
         --query 'Reservations[].Instances[].PublicIpAddress' \
         --output text \
         )
else
IP=$(
        aws ec2 describe-instances \
         --instance-id $InstanceId  \
         --query 'Reservations[].Instances[].PrivateIpAddress' \
         --output text \
         )
fi

done
